package fiberoapi

import (
	"errors"
	"fmt"
	"net/http"
	"reflect"
	"strconv"
	"strings"

	"github.com/gofiber/fiber/v3"
	"gopkg.in/yaml.v3"
)

// DefaultConfig returns the default configuration
func DefaultConfig() Config {
	return Config{
		EnableValidation:   true,
		EnableOpenAPIDocs:  true,
		OpenAPIDocsPath:    "/docs",
		OpenAPIJSONPath:    "/openapi.json",
		OpenAPIYamlPath:    "/openapi.yaml",
		OpenAPITitle:       "Fiber OpenAPI",
		OpenAPIDescription: "API documentation generated by fiber-oapi",
		OpenAPIVersion:     "1.0.0",
	}
}

// New creates a new OApiApp with optional configuration
func New(app *fiber.App, config ...Config) *OApiApp {
	// Use default config if none provided
	cfg := DefaultConfig()
	if len(config) > 0 {
		provided := config[0]

		// Merge provided config with defaults
		// For boolean fields with true defaults, we need special handling
		// We'll only override if the provided config appears to be intentionally configured

		// Simple approach: if the provided config has any non-default values,
		// we assume the user intended to configure it explicitly.
		// Info fields (title/description/version) participate in this signal too so that
		// e.g. `Config{OpenAPITitle: "X", EnableOpenAPIDocs: false}` propagates the
		// explicit `false` to the resolved config (consistency with path fields).
		hasExplicitConfig := provided.EnableAuthorization ||
			provided.AuthService != nil ||
			provided.SecuritySchemes != nil ||
			provided.OpenAPIDocsPath != "" ||
			provided.OpenAPIJSONPath != "" ||
			provided.OpenAPIYamlPath != "" ||
			provided.OpenAPITitle != "" ||
			provided.OpenAPIDescription != "" ||
			provided.OpenAPIVersion != "" ||
			provided.ValidationErrorHandler != nil ||
			provided.AuthErrorHandler != nil ||
			provided.NotFoundHandler != nil ||
			provided.DefaultErrorShape != nil

		// Only override boolean defaults if the config appears to be explicitly set
		if hasExplicitConfig {
			cfg.EnableValidation = provided.EnableValidation
			cfg.EnableOpenAPIDocs = provided.EnableOpenAPIDocs
		}
		// If no explicit config, keep the defaults (true, true, false)

		// Heuristic: when only "metadata" fields (paths, info, handlers — i.e. cosmetic
		// customization that does not signal intent about validation/docs themselves)
		// are provided and all booleans are at their zero value, restore boolean defaults.
		// This avoids surprising users who only want to override the spec title/path but
		// end up with validation silently disabled because Go zero values can't disambiguate
		// "not set" from "set to false". To actually disable validation or docs, set at least
		// one core signal field too (EnableAuthorization / AuthService / SecuritySchemes).
		hasCoreSignal := provided.EnableAuthorization ||
			provided.AuthService != nil ||
			provided.SecuritySchemes != nil

		hasMetadataOnly := !hasCoreSignal && (provided.OpenAPIDocsPath != "" ||
			provided.OpenAPIJSONPath != "" ||
			provided.OpenAPIYamlPath != "" ||
			provided.OpenAPITitle != "" ||
			provided.OpenAPIDescription != "" ||
			provided.OpenAPIVersion != "" ||
			provided.ValidationErrorHandler != nil ||
			provided.AuthErrorHandler != nil ||
			provided.NotFoundHandler != nil ||
			provided.DefaultErrorShape != nil)

		// Only restore defaults if ALL boolean fields are false (suggesting they weren't explicitly set)
		allBooleansAreFalse := !provided.EnableValidation && !provided.EnableOpenAPIDocs && !provided.EnableAuthorization

		if hasMetadataOnly && allBooleansAreFalse {
			cfg.EnableValidation = true  // Restore — caller likely didn't mean to disable it
			cfg.EnableOpenAPIDocs = true // Restore — caller likely didn't mean to disable it
		}

		// For EnableAuthorization: only set to true if explicitly provided
		if provided.EnableAuthorization {
			cfg.EnableAuthorization = provided.EnableAuthorization
		}

		// Non-boolean fields use the original logic
		if provided.OpenAPIDocsPath != "" {
			cfg.OpenAPIDocsPath = provided.OpenAPIDocsPath
		}
		if provided.OpenAPIJSONPath != "" {
			cfg.OpenAPIJSONPath = provided.OpenAPIJSONPath
		}
		if provided.OpenAPIYamlPath != "" {
			cfg.OpenAPIYamlPath = provided.OpenAPIYamlPath
		}
		if provided.OpenAPITitle != "" {
			cfg.OpenAPITitle = provided.OpenAPITitle
		}
		if provided.OpenAPIDescription != "" {
			cfg.OpenAPIDescription = provided.OpenAPIDescription
		}
		if provided.OpenAPIVersion != "" {
			cfg.OpenAPIVersion = provided.OpenAPIVersion
		}
		if provided.AuthService != nil {
			cfg.AuthService = provided.AuthService
		}
		if provided.SecuritySchemes != nil {
			cfg.SecuritySchemes = provided.SecuritySchemes
		}
		if provided.DefaultSecurity != nil {
			cfg.DefaultSecurity = provided.DefaultSecurity
		}
		if provided.ValidationErrorHandler != nil {
			cfg.ValidationErrorHandler = provided.ValidationErrorHandler
		}
		if provided.AuthErrorHandler != nil {
			cfg.AuthErrorHandler = provided.AuthErrorHandler
		}
		if provided.NotFoundHandler != nil {
			cfg.NotFoundHandler = provided.NotFoundHandler
		}
		if provided.DefaultErrorShape != nil {
			cfg.DefaultErrorShape = provided.DefaultErrorShape
		}
		if provided.IncludeInvalidValueInErrors {
			cfg.IncludeInvalidValueInErrors = true
		}
	}

	oapi := &OApiApp{
		f:          app,
		operations: make([]OpenAPIOperation, 0),
		config:     cfg,
	}

	// Automatically setup documentation routes if enabled
	if cfg.EnableOpenAPIDocs {
		oapi.setupDocsRoutes()
	}

	return oapi
}

func (o *OApiApp) setupDocsRoutes() {
	// Serve OpenAPI JSON specification
	o.f.Get(o.Config().OpenAPIJSONPath, func(c fiber.Ctx) error {
		spec := o.GenerateOpenAPISpec()
		c.Set("Content-Type", "application/json")
		return c.JSON(spec)
	})

	// Serve OpenAPI YAML specification
	o.f.Get(o.Config().OpenAPIYamlPath, func(c fiber.Ctx) error {
		spec, err := o.GenerateOpenAPISpecYAML()
		if err != nil {
			return err
		}
		c.Set("Content-Type", "application/yaml")
		return c.SendString(spec)
	})

	// Serve Redoc documentation
	o.f.Get(o.Config().OpenAPIDocsPath, func(c fiber.Ctx) error {
		html := generateRedocHTML(o.Config().OpenAPIJSONPath, "API Documentation")
		c.Set("Content-Type", "text/html")
		return c.SendString(html)
	})

	// Handle trailing slash redirect
	if !strings.HasSuffix(o.Config().OpenAPIDocsPath, "/") {
		o.f.Get(o.Config().OpenAPIDocsPath+"/", func(c fiber.Ctx) error {
			return c.Redirect().To(o.Config().OpenAPIDocsPath)
		})
	}
}

// GetOperations returns all registered operations (useful for testing and documentation generation)
func (o *OApiApp) GetOperations() []OpenAPIOperation {
	return o.operations
}

// GenerateOpenAPISpec generates a complete OpenAPI 3.0 specification
func (o *OApiApp) GenerateOpenAPISpec() map[string]interface{} {
	spec := map[string]interface{}{
		"openapi": "3.0.0",
		"info": map[string]interface{}{
			"title":       o.config.OpenAPITitle,
			"version":     o.config.OpenAPIVersion,
			"description": o.config.OpenAPIDescription,
		},
		"paths":      make(map[string]interface{}),
		"components": make(map[string]interface{}),
	}

	paths := spec["paths"].(map[string]interface{})
	components := spec["components"].(map[string]interface{})
	schemas := make(map[string]interface{})
	components["schemas"] = schemas

	// Add security schemes if configured
	if len(o.config.SecuritySchemes) > 0 {
		components["securitySchemes"] = o.config.SecuritySchemes
	}

	// Add default security if configured
	if len(o.config.DefaultSecurity) > 0 {
		spec["security"] = o.config.DefaultSecurity
	}

	// First pass: collect all types that need schemas
	allTypes := make(map[string]reflect.Type)

	for _, op := range o.operations {
		if op.InputType != nil {
			collectAllTypes(op.InputType, allTypes)
		}
		if op.OutputType != nil {
			collectAllTypes(op.OutputType, allTypes)
		}
		if op.ErrorType != nil && !isEmptyStruct(op.ErrorType) {
			collectAllTypes(op.ErrorType, allTypes)
		}
		// Each declared custom error contributes its own type to components.schemas
		// so multiple error responses sharing a struct ($ref via the same name)
		// stay deduplicated.
		for _, errInst := range op.Options.Errors {
			if errInst == nil {
				continue
			}
			collectAllTypes(reflect.TypeOf(errInst), allTypes)
		}
	}

	// When the user opted into a unified shape via Config.DefaultErrorShape, the
	// per-operation responses below reference it by $ref. Make sure its schema
	// (and any nested types) is collected so we never emit dangling references.
	if o.config.DefaultErrorShape != nil {
		collectAllTypes(reflect.TypeOf(o.config.DefaultErrorShape), allTypes)
	}

	// Second pass: generate all schemas
	for typeName, typeInfo := range allTypes {
		schemas[typeName] = generateSchema(typeInfo)
	}

	// Always expose the default error envelope shape so every route can $ref it.
	collectAllTypes(reflect.TypeOf(ErrorEnvelope{}), allTypes)
	if _, ok := schemas["ErrorEnvelope"]; !ok {
		schemas["ErrorEnvelope"] = generateSchema(reflect.TypeOf(ErrorEnvelope{}))
	}
	if _, ok := schemas["ValidationErrorEntry"]; !ok {
		schemas["ValidationErrorEntry"] = generateSchema(reflect.TypeOf(ValidationErrorEntry{}))
	}
	if _, ok := schemas["ResponseContext"]; !ok {
		schemas["ResponseContext"] = generateSchema(reflect.TypeOf(ResponseContext{}))
	}

	for _, op := range o.operations {
		// Convert Fiber path format (:param) to OpenAPI format ({param})
		openAPIPath := convertFiberPathToOpenAPI(op.Path)

		if paths[openAPIPath] == nil {
			paths[openAPIPath] = make(map[string]interface{})
		}

		pathItem := paths[openAPIPath].(map[string]interface{})

		// Copy the options and enhance them with auto-generated schemas
		enhancedOptions := make(map[string]interface{})

		// Copy existing options
		if op.Options.OperationID != "" {
			enhancedOptions["operationId"] = op.Options.OperationID
		}
		if op.Options.Summary != "" {
			enhancedOptions["summary"] = op.Options.Summary
		}
		if op.Options.Description != "" {
			enhancedOptions["description"] = op.Options.Description
		}
		if len(op.Options.Tags) > 0 {
			enhancedOptions["tags"] = op.Options.Tags
		}

		// Auto-generate parameters from struct tags and merge with manual parameters
		autoParameters := []map[string]interface{}{}
		if op.InputType != nil {
			autoParameters = extractParametersFromStruct(op.InputType)
		}

		// Merge auto-generated parameters with manually defined ones
		allParameters := autoParameters
		if len(op.Options.Parameters) > 0 {
			allParameters = mergeParameters(autoParameters, op.Options.Parameters)
		}

		if len(allParameters) > 0 {
			enhancedOptions["parameters"] = allParameters
		}

		// Add security information
		if op.Options.Security != nil {
			if securityValue, ok := op.Options.Security.(string); ok && securityValue == "disabled" {
				// Explicitly set empty security to override defaults
				enhancedOptions["security"] = []map[string][]string{}
			} else if securitySlice, ok := op.Options.Security.([]map[string][]string); ok {
				enhancedOptions["security"] = securitySlice
			}
		}

		// Add required roles as OpenAPI extension
		if len(op.Options.RequiredRoles) > 0 {
			enhancedOptions["x-required-roles"] = op.Options.RequiredRoles
			if op.Options.RequireAllRoles {
				enhancedOptions["x-required-roles-mode"] = "all"
			} else {
				enhancedOptions["x-required-roles-mode"] = "any"
			}
		}

		// Add descriptions for required permissions
		if len(op.Options.RequiredPermissions) > 0 {
			desc := ""
			if op.Options.Description != "" {
				desc = op.Options.Description
			}
			desc += fmt.Sprintf("\n\n**Required Permissions:** %s", strings.Join(op.Options.RequiredPermissions, ", "))
			enhancedOptions["description"] = desc
		}

		// Add request body schema for POST/PUT methods
		if op.Method == "POST" || op.Method == "PUT" || op.Method == "PATCH" {
			if op.InputType != nil {
				inputType := dereferenceType(op.InputType)

				var schemaRef map[string]interface{}

				if shouldInlineOperationSchema(inputType) {
					schemaRef = generateSchema(inputType)
				} else {
					inputSchemaName := getTypeName(inputType)
					schemaRef = map[string]interface{}{
						"$ref": "#/components/schemas/" + inputSchemaName,
					}
				}

				enhancedOptions["requestBody"] = map[string]interface{}{
					"required": true,
					"content": map[string]interface{}{
						"application/json": map[string]interface{}{
							"schema": schemaRef,
						},
					},
				}
			}
		}

		// Add response schemas
		responses := make(map[string]interface{})

		// Success response (200)
		if op.OutputType != nil {
			outputType := dereferenceType(op.OutputType)

			var schemaRef map[string]interface{}

			if shouldInlineOperationSchema(outputType) {
				schemaRef = generateSchema(outputType)
			} else {
				outputSchemaName := getTypeName(outputType)
				schemaRef = map[string]interface{}{
					"$ref": "#/components/schemas/" + outputSchemaName,
				}
			}

			responses["200"] = map[string]interface{}{
				"description": "Successful response",
				"content": map[string]interface{}{
					"application/json": map[string]interface{}{
						"schema": schemaRef,
					},
				},
			}
		}

		// A route can opt out of every framework-emitted error response (the 4XX
		// catch-all, 400 parse, 422 validation, 404 not-found) by passing an
		// explicit empty slice — `Errors: []any{}`. This is the canonical way
		// to document an endpoint like /health that has no error contract at all.
		//
		// We distinguish nil (field not set → default behaviour) from a non-nil
		// empty slice (user explicitly says "no errors"). A slice with only nil
		// entries still counts as "not declared" — same reasoning as the legacy
		// 4XX guard below.
		suppressAllDefaultErrors := op.Options.Errors != nil && len(op.Options.Errors) == 0

		// Custom TError response — only when the handler returns a non-empty TError.
		// Emitted as a 4XX catch-all so legacy users who do not declare per-status
		// entries via OpenAPIOptions.Errors still get their domain error documented.
		//
		// When the route DOES declare at least one non-nil Errors entry, the 4XX
		// is redundant (and worse, misleading): the user has explicitly enumerated
		// the status codes their handler can emit, so the catch-all just pollutes
		// the spec. Count non-nil entries — a slice that only contains nil is
		// equivalent to no declaration since the emission loop below would skip
		// every entry, leaving the route with zero documented error responses.
		if op.ErrorType != nil && !isEmptyStruct(op.ErrorType) && !hasNonNilErrorEntry(op.Options.Errors) && !suppressAllDefaultErrors {
			errorType := dereferenceType(op.ErrorType)

			var schemaRef map[string]interface{}
			if shouldInlineOperationSchema(errorType) {
				schemaRef = generateSchema(errorType)
			} else {
				schemaRef = map[string]interface{}{
					"$ref": "#/components/schemas/" + getTypeName(errorType),
				}
			}

			responses["4XX"] = map[string]interface{}{
				"description": "Domain error returned by the handler",
				"content": map[string]interface{}{
					"application/json": map[string]interface{}{
						"schema": schemaRef,
					},
				},
			}
		}

		// Default error responses produced by parseInput. When the user opted
		// into a unified shape via Config.DefaultErrorShape, every default entry
		// uses that shape (schema + a representative example built via the same
		// reflection helpers used at runtime). Otherwise we fall back to the
		// built-in ErrorEnvelope.
		shape := o.config.DefaultErrorShape
		defaultErrContent := func(cat errorCategory, envExample func() ErrorEnvelope) map[string]interface{} {
			if shape != nil {
				return map[string]interface{}{
					"schema":  errorSchemaRef(reflect.TypeOf(shape)),
					"example": materializeError(shape, cat),
				}
			}
			return map[string]interface{}{
				"schema":  map[string]interface{}{"$ref": "#/components/schemas/ErrorEnvelope"},
				"example": envExample(),
			}
		}

		// All three default envelope responses (422 validation, 400 parse,
		// 404 not-found) honour the opt-out so a /health-style endpoint can
		// document just its 200.
		if !suppressAllDefaultErrors {
			// 422 always uses ErrorEnvelope so per-field info (loc / constraint /
			// field / value) stays first-class for clients building form-level UX,
			// even when DefaultErrorShape is set for the other error categories.
			responses["422"] = map[string]interface{}{
				"description": "Validation error",
				"content": map[string]interface{}{
					"application/json": map[string]interface{}{
						"schema":  map[string]interface{}{"$ref": "#/components/schemas/ErrorEnvelope"},
						"example": exampleValidationEnvelope(),
					},
				},
			}
			// Only POST/PUT/PATCH can produce JSON parse / type-mismatch errors.
			// The 400 covers both syntactically-malformed bodies and well-formed
			// bodies whose fields have the wrong JSON type — the example uses the
			// type-mismatch form because it's the most common in practice and the
			// most useful to show clients.
			if op.Method == "POST" || op.Method == "PUT" || op.Method == "PATCH" {
				responses["400"] = map[string]interface{}{
					"description": "Invalid request body (malformed JSON or wrong field type)",
					"content": map[string]interface{}{"application/json": defaultErrContent(errorCategory{
						Code:    400,
						Type:    errTypeTypeMismatch,
						Message: fmt.Sprintf(typeMismatchMsgFmt, "age", "int", "string"),
						Details: "int",
					}, exampleParseEnvelope)},
				}
			}
			// When UseNotFoundHandler() has been installed, every operation can
			// surface the same shape under 404 — document it.
			if o.notFoundInstalled {
				responses["404"] = map[string]interface{}{
					"description": "Route not found",
					"content": map[string]interface{}{"application/json": defaultErrContent(errorCategory{
						Code:    404,
						Type:    errTypeNotFound,
						Message: "no route matches GET /users/42",
					}, exampleNotFoundEnvelope)},
				}
			}
		}
		// Per-route custom errors declared via OpenAPIOptions.Errors. Each instance
		// produces a response entry keyed by its status code, taking precedence over
		// any default envelope entry for the same code so the user-provided shape
		// is what the spec advertises.
		for _, errInst := range op.Options.Errors {
			if errInst == nil {
				continue
			}
			code, response := buildErrorResponse(errInst)
			responses[statusCodeKey(code)] = response
		}

		enhancedOptions["responses"] = responses
		pathItem[strings.ToLower(op.Method)] = enhancedOptions
	}

	return spec
}

// GenerateOpenAPISpecYAML generates the OpenAPI spec in YAML format
func (o *OApiApp) GenerateOpenAPISpecYAML() (string, error) {
	spec := o.GenerateOpenAPISpec()
	yamlData, err := yaml.Marshal(spec)
	if err != nil {
		return "", err
	}
	return string(yamlData), nil
}

// collectAllTypes recursively collects all types referenced by a given type
func collectAllTypes(t reflect.Type, collected map[string]reflect.Type) {
	if t == nil {
		return
	}

	// Handle pointers
	t = dereferenceType(t)

	// time.Time is rendered inline as a date-time string, not as a component schema
	if isTimeType(t) {
		return
	}

	typeName := getTypeName(t)
	if typeName == "" {
		return
	}

	// Skip if already processed
	if _, exists := collected[typeName]; exists {
		return
	}

	// Handle different kinds of types
	switch t.Kind() {
	case reflect.Struct:
		// Only add structs that have a meaningful name
		if typeName != "EmptyObject" && typeName != "AnonymousStruct" {
			collected[typeName] = t
		}

		// Recursively collect types from all fields
		for i := 0; i < t.NumField(); i++ {
			field := t.Field(i)
			if !field.IsExported() {
				continue
			}

			// Skip fields hidden from OpenAPI documentation
			if field.Tag.Get("openapi") == "-" {
				continue
			}

			// Skip fields with json:"-" tag
			if jsonTag := field.Tag.Get("json"); jsonTag == "-" {
				continue
			}

			collectAllTypes(field.Type, collected)
		}

	case reflect.Map:
		// Don't add map types as separate schemas - they're always inlined
		// Just collect key and value types recursively
		keyType := t.Key()
		valueType := t.Elem()

		collectAllTypes(keyType, collected)
		collectAllTypes(valueType, collected)

	case reflect.Slice:
		// Add slice type for complex slices
		if shouldGenerateSchemaForType(t) {
			collected[typeName] = t
		}

		// Collect element type
		collectAllTypes(t.Elem(), collected)

	case reflect.Interface:
		// For interface{}, we might want to document it
		if t.NumMethod() == 0 && shouldGenerateSchemaForType(t) {
			collected[typeName] = t
		}

	default:
		// For basic types, we usually don't need separate schemas
		// but if they have a name, they might be custom types
		if t.Name() != "" && shouldGenerateSchemaForType(t) {
			collected[typeName] = t
		}
	}
}

// shouldGenerateSchemaForType determines if a type should get its own schema
func shouldGenerateSchemaForType(t reflect.Type) bool {
	if t == nil {
		return false
	}

	// Handle pointers
	t = dereferenceType(t)

	switch t.Kind() {
	case reflect.Struct:
		// Always generate schema for structs (except empty ones)
		return t.NumField() > 0
	case reflect.Map:
		// Generate schema for maps with complex value types
		valueType := dereferenceType(t.Elem())
		return valueType.Kind() == reflect.Struct ||
			valueType.Kind() == reflect.Map ||
			valueType.Kind() == reflect.Slice
	case reflect.Slice:
		// Generate schema for slices of complex types
		elemType := dereferenceType(t.Elem())
		return elemType.Kind() == reflect.Struct ||
			elemType.Kind() == reflect.Map
	case reflect.Interface:
		// Generate schema for interface{} to document it properly
		return t.NumMethod() == 0
	default:
		// For basic types, only if they're named custom types
		return t.Name() != "" && t.PkgPath() != ""
	}
}

// convertFiberPathToOpenAPI converts Fiber path format to OpenAPI format
// Example: /users/:id/posts/:postId -> /users/{id}/posts/{postId}
func convertFiberPathToOpenAPI(fiberPath string) string {
	// Replace :param with {param}
	parts := strings.Split(fiberPath, "/")

	for i, part := range parts {
		if strings.HasPrefix(part, ":") {
			parts[i] = "{" + part[1:] + "}"
		}
	}

	return strings.Join(parts, "/")
}

// getTypeName returns the name of a Go type for use in OpenAPI schema names
func getTypeName(t reflect.Type) string {
	if t == nil {
		return "EmptyObject"
	}

	// Handle pointers
	t = dereferenceType(t)

	// Handle different kinds of types
	switch t.Kind() {
	case reflect.Map:
		// For maps, create a descriptive name
		keyType := t.Key()
		valueType := t.Elem()
		return fmt.Sprintf("Map_%s_%s",
			getSimpleTypeName(keyType),
			getSimpleTypeName(valueType))
	case reflect.Slice:
		// For slices, create a descriptive name
		elemType := t.Elem()
		return fmt.Sprintf("Array_%s", getSimpleTypeName(elemType))
	case reflect.Interface:
		// For interfaces, use a generic name
		if t.NumMethod() == 0 {
			return "AnyValue" // interface{}
		}
		return "Interface"
	default:
		name := t.Name()
		if name == "" {
			// For anonymous structs, use the package path + "AnonymousStruct"
			if t.Kind() == reflect.Struct {
				return "AnonymousStruct"
			}
			return getSimpleTypeName(t)
		}
		return name
	}
}

// getSimpleTypeName returns a simple name for basic types
func getSimpleTypeName(t reflect.Type) string {
	if t == nil {
		return "Any"
	}

	// Handle pointers
	t = dereferenceType(t)

	switch t.Kind() {
	case reflect.String:
		return "String"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return "Integer"
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return "UInteger"
	case reflect.Float32, reflect.Float64:
		return "Number"
	case reflect.Bool:
		return "Boolean"
	case reflect.Interface:
		return "Any"
	case reflect.Map:
		return "Object"
	case reflect.Slice:
		return "Array"
	case reflect.Struct:
		if name := t.Name(); name != "" {
			return name
		}
		return "Object"
	default:
		return "Any"
	}
}

// isTimeType reports whether t is the standard library time.Time type.
func isTimeType(t reflect.Type) bool {
	return t != nil && t.Kind() == reflect.Struct && t.Name() == "Time" && t.PkgPath() == "time"
}

// shouldInlineOperationSchema reports whether a top-level request, response,
// or error body schema should be inlined rather than emitted as a $ref to
// #/components/schemas/. It mirrors the registration logic in collectAllTypes:
// types that never end up in the components map (primitives, maps, time.Time,
// slices of inlinable elements) must be inlined to avoid dangling $refs.
func shouldInlineOperationSchema(t reflect.Type) bool {
	if t == nil {
		return false
	}
	t = dereferenceType(t)
	if isTimeType(t) {
		return true
	}
	switch t.Kind() {
	case reflect.Map:
		return true
	case reflect.String, reflect.Bool,
		reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return true
	case reflect.Slice:
		return shouldInlineOperationSchema(t.Elem())
	}
	return false
}

// generateSchema generates an OpenAPI schema from a Go type
func generateSchema(t reflect.Type) map[string]interface{} {
	if t == nil {
		return map[string]interface{}{
			"type": "object",
		}
	}

	// Handle pointers
	t = dereferenceType(t)

	if isTimeType(t) {
		return map[string]interface{}{
			"type":    "string",
			"format":  "date-time",
			"example": "2006-01-02T15:04:05Z",
		}
	}

	schema := make(map[string]interface{})

	switch t.Kind() {
	case reflect.Struct:
		schema["type"] = "object"
		properties := make(map[string]interface{})
		required := []string{}

		for i := 0; i < t.NumField(); i++ {
			field := t.Field(i)
			if !field.IsExported() {
				continue
			}

			// Skip fields hidden from OpenAPI documentation
			if field.Tag.Get("openapi") == "-" {
				continue
			}

			// Skip fields that are path, query, or header parameters - they are handled separately
			if field.Tag.Get("path") != "" || field.Tag.Get("query") != "" || field.Tag.Get("header") != "" {
				continue
			}

			// Get JSON tag name
			jsonTag := field.Tag.Get("json")
			if jsonTag == "-" {
				continue
			}

			fieldName := field.Name
			if jsonTag != "" {
				parts := strings.Split(jsonTag, ",")
				if parts[0] != "" {
					fieldName = parts[0]
				}
			}

			// Generate field schema
			fieldSchema := generateFieldSchema(field.Type)

			// Add validation info from tags
			if validateTag := field.Tag.Get("validate"); validateTag != "" {
				addValidationToSchema(fieldSchema, validateTag)

				// Check if field is required
				if strings.Contains(validateTag, "required") {
					required = append(required, fieldName)
				}
			}

			properties[fieldName] = fieldSchema
		}

		schema["properties"] = properties
		if len(required) > 0 {
			schema["required"] = required
		}

	case reflect.Map:
		// Handle map types (like map[string]string, map[string]interface{}) - use inline schemas
		schema["type"] = "object"
		keyType := t.Key()
		valueType := t.Elem()

		// For string keys, we can use additionalProperties
		if keyType.Kind() == reflect.String {
			if valueType.Kind() == reflect.Interface && valueType.NumMethod() == 0 {
				// For interface{}, allow any type
				schema["additionalProperties"] = true
				schema["example"] = map[string]interface{}{
					"string_key":  "string_value",
					"number_key":  42,
					"boolean_key": true,
				}
			} else {
				schema["additionalProperties"] = generateFieldSchema(valueType)
				// Add example for common map types
				if valueType.Kind() == reflect.String {
					schema["example"] = map[string]string{
						"key1": "value1",
						"key2": "value2",
					}
				}
			}
		} else {
			// For non-string keys, treat as generic object
			schema["additionalProperties"] = true
		}

	case reflect.Interface:
		// Handle interface{} types - treat as any value
		schema["description"] = "Any value (interface{})"
		// Don't specify type to allow any JSON value

	case reflect.String:
		schema["type"] = "string"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		schema["type"] = "integer"
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		schema["type"] = "integer"
		schema["minimum"] = 0
	case reflect.Float32, reflect.Float64:
		schema["type"] = "number"
	case reflect.Bool:
		schema["type"] = "boolean"
	case reflect.Slice:
		schema["type"] = "array"
		schema["items"] = generateFieldSchema(t.Elem())
	default:
		// Fallback for unknown types
		schema["type"] = "object"
		schema["description"] = fmt.Sprintf("Unknown type: %s", t.Kind().String())
	}

	return schema
}

// generateFieldSchema generates schema for a struct field
func generateFieldSchema(t reflect.Type) map[string]interface{} {
	schema := make(map[string]interface{})

	// Handle pointers
	t = dereferenceType(t)

	if isTimeType(t) {
		schema["type"] = "string"
		schema["format"] = "date-time"
		schema["example"] = "2006-01-02T15:04:05Z"
		return schema
	}

	switch t.Kind() {
	case reflect.String:
		schema["type"] = "string"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		schema["type"] = "integer"
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		schema["type"] = "integer"
		schema["minimum"] = 0
	case reflect.Float32, reflect.Float64:
		schema["type"] = "number"
	case reflect.Bool:
		schema["type"] = "boolean"
	case reflect.Slice:
		schema["type"] = "array"
		schema["items"] = generateFieldSchema(t.Elem())
	case reflect.Map:
		// Handle map types in fields - always use inline schemas to avoid reference issues
		schema["type"] = "object"
		keyType := t.Key()
		valueType := t.Elem()

		// For string keys, we can use additionalProperties
		if keyType.Kind() == reflect.String {
			if valueType.Kind() == reflect.Interface && valueType.NumMethod() == 0 {
				// For interface{}, allow any type
				schema["additionalProperties"] = true
				schema["example"] = map[string]interface{}{
					"string_key":  "string_value",
					"number_key":  42,
					"boolean_key": true,
				}
			} else {
				schema["additionalProperties"] = generateFieldSchema(valueType)
				// Add example for common map types
				if valueType.Kind() == reflect.String {
					schema["example"] = map[string]string{
						"key": "value",
					}
				}
			}
		} else {
			// For non-string keys, treat as generic object
			schema["additionalProperties"] = true
		}
	case reflect.Interface:
		// Handle interface{} types
		schema["description"] = "Any value (interface{})"
		// Don't specify type to allow any JSON value
	case reflect.Struct:
		// For nested structs, reference the type name
		typeName := getTypeName(t)
		if typeName == "" || typeName == "EmptyObject" {
			// For anonymous or empty structs, inline as object
			schema["type"] = "object"
		} else {
			schema["$ref"] = "#/components/schemas/" + typeName
		}
	default:
		// Fallback for unknown types
		schema["type"] = "object"
		schema["description"] = fmt.Sprintf("Unsupported type: %s", t.Kind().String())
	}

	return schema
}

// addValidationToSchema adds validation constraints to schema based on validate tags
func addValidationToSchema(schema map[string]interface{}, validateTag string) {
	rules := strings.Split(validateTag, ",")

	for _, rule := range rules {
		rule = strings.TrimSpace(rule)

		if rule == "required" {
			// Required is handled at the object level
			continue
		} else if strings.HasPrefix(rule, "min=") {
			if val := strings.TrimPrefix(rule, "min="); val != "" {
				if schema["type"] == "string" {
					schema["minLength"] = parseIntOrZero(val)
				} else if schema["type"] == "integer" || schema["type"] == "number" {
					schema["minimum"] = parseIntOrZero(val)
				}
			}
		} else if strings.HasPrefix(rule, "max=") {
			if val := strings.TrimPrefix(rule, "max="); val != "" {
				if schema["type"] == "string" {
					schema["maxLength"] = parseIntOrZero(val)
				} else if schema["type"] == "integer" || schema["type"] == "number" {
					schema["maximum"] = parseIntOrZero(val)
				}
			}
		} else if rule == "email" {
			schema["format"] = "email"
		} else if rule == "uuid4" {
			schema["format"] = "uuid"
		} else if rule == "url" {
			schema["format"] = "uri"
		} else if strings.HasPrefix(rule, "oneof=") {
			if val := strings.TrimPrefix(rule, "oneof="); val != "" {
				values := strings.Split(val, " ")
				schema["enum"] = values
			}
		}
	}
}

// parseIntOrZero parses a string to int, returns 0 if parsing fails
func parseIntOrZero(s string) int {
	if val, err := strconv.Atoi(s); err == nil {
		return val
	}
	return 0
}

// isEmptyStruct checks if a type represents an empty struct
func isEmptyStruct(t reflect.Type) bool {
	if t == nil {
		return true
	}

	t = dereferenceType(t)

	return t.Kind() == reflect.Struct && t.NumField() == 0
}

// Method defines a generic method for registering HTTP operations with OpenAPI documentation
func Method[TInput any, TOutput any, TError any](
	router OApiRouter, // Interface instead of *OApiApp
	m string,
	path string,
	handler HandlerFunc[TInput, TOutput, TError],
	options OpenAPIOptions,
) {
	app := router.GetApp()
	fullPath := router.GetPrefix() + path

	// Validate path parameters with the input struct
	if err := validatePathParams[TInput](fullPath); err != nil {
		panic(fmt.Sprintf("Path validation failed for %s: %v", fullPath, err))
	}

	// Register the operation for OpenAPI documentation with type information
	var inputZero TInput
	var outputZero TOutput
	var errorZero TError

	app.operations = append(app.operations, OpenAPIOperation{
		Method:     m,
		Path:       fullPath,
		Options:    options,
		InputType:  reflect.TypeOf(inputZero),
		OutputType: reflect.TypeOf(outputZero),
		ErrorType:  reflect.TypeOf(errorZero),
	})

	inputType := reflect.TypeOf(inputZero)

	// Wrapper
	fiberHandler := func(c fiber.Ctx) error {
		input, err := parseInput[TInput](app, c, fullPath, &options)
		if err != nil {
			// Custom handlers, when configured, still take precedence and receive
			// the raw error — they may produce any shape they want.
			if authErr, ok := errors.AsType[*AuthError](err); ok && app.config.AuthErrorHandler != nil {
				return app.config.AuthErrorHandler(c, authErr)
			}
			if app.config.ValidationErrorHandler != nil {
				return app.config.ValidationErrorHandler(c, err)
			}
			// If the user opted into a unified shape, emit it for parse / auth /
			// generic errors. Validation errors keep the rich ErrorEnvelope shape
			// regardless — collapsing a multi-field validation failure into a
			// single flat struct would lose the per-field info (loc / constraint
			// / field) that clients rely on for form-level UX.
			if app.config.DefaultErrorShape != nil && !isValidationError(err) {
				cat := categorizeError(err)
				return c.Status(cat.Code).JSON(materializeError(app.config.DefaultErrorShape, cat))
			}
			// Default response: structured envelope, one entry per failing field,
			// status code chosen per error category (422 validation, 400 parse,
			// 401/403 auth).
			envelope, status := buildEnvelope(c, app.config, inputType, err)
			return c.Status(status).JSON(envelope)
		}

		output, customErr := handler(c, input)

		if !isZero(customErr) {
			return handleCustomError(c, customErr)
		}

		if err := c.JSON(output); err != nil {
			if fallbackErr := c.Status(500).JSON(ErrorResponse{
				Code:    500,
				Details: "Failed to serialize response",
				Type:    "serialization_error",
			}); fallbackErr != nil {
				// Both serializations failed, return original error to Fiber
				return err
			}
			return nil
		}
		return nil
	}

	app.f.Add([]string{m}, fullPath, fiberHandler)
}

// Get defines a GET operation for the OpenAPI documentation
func Get[TInput any, TOutput any, TError any](
	router OApiRouter, // Now accepts both *OApiApp and *OApiGroup
	path string,
	handler HandlerFunc[TInput, TOutput, TError],
	options OpenAPIOptions,
) {
	Method(router, http.MethodGet, path, handler, options)
}

// Post defines a POST operation for the OpenAPI documentation
func Post[TInput any, TOutput any, TError any](
	router OApiRouter, // Now accepts both *OApiApp and *OApiGroup
	path string,
	handler HandlerFunc[TInput, TOutput, TError],
	options OpenAPIOptions,
) {
	Method(router, http.MethodPost, path, handler, options)
}

// Put defines a PUT operation for the OpenAPI documentation
func Put[TInput any, TOutput any, TError any](
	router OApiRouter, // Now accepts both *OApiApp and *OApiGroup
	path string,
	handler HandlerFunc[TInput, TOutput, TError],
	options OpenAPIOptions,
) {
	Method(router, http.MethodPut, path, handler, options)
}

// Delete defines a DELETE operation for the OpenAPI documentation
func Delete[TInput any, TOutput any, TError any](
	router OApiRouter, // Now accepts both *OApiApp and *OApiGroup
	path string,
	handler HandlerFunc[TInput, TOutput, TError],
	options OpenAPIOptions,
) {
	Method(router, http.MethodDelete, path, handler, options)
}

// Head defines a HEAD operation for the OpenAPI documentation
func Head[TInput any, TOutput any, TError any](
	router OApiRouter, // Now accepts both *OApiApp and *OApiGroup
	path string,
	handler HandlerFunc[TInput, TOutput, TError],
	options OpenAPIOptions,
) {
	Method(router, http.MethodHead, path, handler, options)
}

// Patch defines a PATCH operation for the OpenAPI documentation
func Patch[TInput any, TOutput any, TError any](
	router OApiRouter, // Now accepts both *OApiApp and *OApiGroup
	path string,
	handler HandlerFunc[TInput, TOutput, TError],
	options OpenAPIOptions,
) {
	Method(router, http.MethodPatch, path, handler, options)
}
